### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by SzymenL0K0** [qwerty-mods/double-click-vc#1]
Discord Stable 235028 (8688a61) Host 1.0.9018 x86 (37723) Windows 10 64-Bit (10.0.19045)
Replugged v4.6.5
double click to VC 1.0.2
It's just not working. Have it tongle on.
This list of my plugins so i dont think its colidate with something 
![obraz](https://github.com/qwerty-mods/double-click-vc/assets/35821006/3dc0d0cb-c74b-428e-affa-3de99c324c0c)

**Comment by Kalumel** [comment]
got the same issue.

**Comment by yofukashino** [comment]
old issue
